version: 2
jobs:
  build:
    working-directory: ~/factionsfly
    docker:
      - image: circleci/openjdk:8u181-jdk
    steps:
      - checkout
      - run: mvn clean install
      - store_artifacts:
          path: target/*.jar
workflows:
  version: 2
  workflow:
    jobs:
      - build